### ISSUE TITLE
无论什么检索内容，均为0页

### ISSUE THREAD

**Issue by demostars** [will4906/PatentCrawler#5]
您好，首先感谢此项目，非常棒~

反馈一个问题，不知道是否是个例，账号密码填写正确后，无论检索什么内容，包括示例程序的“人工智能”均显示 

共0 页
finished

是否是我的原因，需要我提供什么以供排查么？

感谢~

**Comment by poppy977** [comment]
您好，非常感谢您的项目！
反馈同样的问题，无论检索什么内容，都是共0页
应该是没有登录成功，但还不确定是哪一步出错了

谢谢~

**Comment by Krimony** [comment]
您好，首先感谢此项目！
我也是之前可以检索到，但是现在不能用了，还有个问题，可以自定义数据库字段吗，有好多是空的想把这些字段删掉
感谢～

**Comment by will4906** [comment]
统一回复，可能网站某些东西发生了变更，我将在年后进行一次大规模更新，谢谢大家的反馈。

**Comment by irance** [comment]
遇到了相同的问题，似乎是登陆的问题，正在尝试修复

**Comment by kserjin** [comment]
遇到了同样的问题，是不是因为命令行搜索必须要高级用户了？以前可以普通用户吗？

**Comment by irance** [comment]
似乎是cookies认证的问题，自己写如果用爬虫搞就会直接失效
